Update SECURITY.md
zvonimirr/tenantee pull request #261
Opened 2023-02-12 16:26 UTC by mithindev

Refactor security policy 

- Add instructions for reporting a vulnerability 
- Refine the secure development process
- Clarify the responsible disclosure guidelines 
- Update the versioning information to 1.0 

This commit updates the security policy to ensure that the Tenantee platform is secure and that security vulnerabilities are reported and addressed in a responsible manner.

2023-02-12 16:27 UTC, mithindev reviewed
Reviewed for checking!

2023-02-12 18:55 UTC, zvonimirr requested changes
You can set the proper email, otherwise it looks good

2023-02-12 18:55 UTC, zvonimirr commented on SECURITY.md
> +If you discover a security vulnerability, please send an email to zvonimirr@example.com to notify the Tenantee security team. The security team will work with you to acknowledge receipt of the report
```suggestion
If you discover a security vulnerability, please send an email to zvonimir.rudinski@noubis.com to notify the Tenantee security team. The security team will work with you to acknowledge receipt of the report and to resolve the vulnerability as quickly as possible.
```

2023-02-13 00:30 UTC, mithindev commented
Hello @zvonimirr I have resolved the issue. Thank you for reviewing.

2023-02-15 00:59 UTC, zvonimirr approved these changes

2023-02-15 01:00 UTC, zvonimirr commented
@allcontributors please add @mithindev for documentation

2023-02-15 01:01 UTC, merged